CC = gcc
CFLAGS = -Wall -Wextra -pthread
TARGET = proxy_server

all: $(TARGET)

$(TARGET): proxy.c cache.c backend_servers.c thread_pool.c
	$(CC) $(CFLAGS) -o $(TARGET) proxy.c cache.c backend_servers.c thread_pool.c

clean:
	rm -f $(TARGET)