CC = gcc
CFLAGS = -Wall -Wextra -pthread
TARGET = proxy_server

all: $(TARGET)

$(TARGET): main.c proxy.c thread_pool.c
	$(CC) $(CFLAGS) -o $(TARGET) main.c proxy.c thread_pool.c

clean:
	rm -f $(TARGET)
